config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users

  resources :users, only: [:index,:show,:edit,:update]
  resources :books, only: [:index,:show,:edit,:create,:update,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user_book, only: [:edit,:update,:destroy]

  def index
    @book = current_user.books.new
    @books = Book.all
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

  def is_matching_login_user_book
    book = Book.find(params[:id])
    if book.user_id != current_user.id
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">

  <h2>User info</h2>
  <%= image_tag book.user.get_profile_image(100,100) %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= book.user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= book.user.introduction %></th>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <% if current_user.id == book.user.id %>
      <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block edit_user_#{current_user.id}" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% else %>
      <%= link_to edit_user_path(book.user_id), class: "btn btn-outline-secondary btn-block edit_user_#{book.user_id}" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% end %>
  </div>

  <h2 class="mt-3">New book</h2>

  <%= form_with model: book, url: books_path, method: :post do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title,class: "form-control book_title", value: "" %>
    </div>
    <div class="form-group">
      <%= f.label :opinion %>
      <%= f.text_area :body, id: "book_body",class: "form-control book_body", value: "" %>
    </div>
    <div class="form-group">
      <%= f.submit "Create Book",class: "btn btn-success" %>
    </div>
  <% end %>

</div>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>

    <div id="error_explanation">
      <% if @book.errors.any? %>
        <% if @book.errors.count == 1 %>
          <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
        <% else %>
          <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <% end %>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <%= form_with model: @book do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title,class: "form-control book_title",id: "book_title" %>
      </div>
      <div class="form-group">
        <%= f.label :opinion %>
        <%= f.text_area :body,class: "form-control book_body",id: "opinion" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>
    <% end %>

    <%= link_to "Show", book_path(@book.id) %> |
    <%= link_to "Back", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<div id="error_explanation">
  <% if @book.errors.any? %>
    <% if @book.errors.count == 1 %>
      <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
    <% else %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
    <% end %>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div class="row">
  <%= render "list", book: @book %>
  
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image(80,80) %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">
  <%= render "list", book: @book %>

  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table table-hover table-inverse">
      <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user_id) do %>
                <%= image_tag @book.user.get_profile_image(100,100) %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <% if @book.user.id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book.id),class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
              <td><%= link_to "Destroy", book_path(@book.id),method: :delete,class: "btn btn-sm btn-danger destroy_book_#{@book.id}","data-confirm" => "本当に消しますか？" %></td>
            <% end %>
          </tr>
      </tbody>
    </table>
  </div>
</div>