config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users

  resources :users, only: [:index,:show,:edit,:update]
  resources :books, only: [:index,:show,:edit,:create,:update,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/f391cbb1de.js" crossorigin="anonymous"></script>
  </head>

  <body>

    <!--ヘッダー-->
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <span>
            <%= link_to "Bookers", root_path ,class: "navbar-brand" %>
          </span>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: "nav-link text-light" do %>
                    <i class="fas fa-users"></i> Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: "nav-link text-light" do %>
                    <i class="fas fa-book-open"></i> Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to home_about_path, class: "nav-link text-light" do %>
                    <i class="fas fa-link"></i></i> About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                    <i class="fas fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <!--メイン-->
    <main>
      <p id="notice"><%= flash[:notice] %></p>

      <div class="container px-5 px-sm-0">

        <%= yield %>

      </div>
    </main>

    <!--フッター-->
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>